EXPERIMENT - 11

Create DataSet and load dataset in Panda's Library

Name:- Aadit Joshi

25070123173

In [ ]:
#Dataset creation
import pandas as pd

data={
    "Roll_No":[101,102,103,104,105],
    "Gender":["F","M","F","M","F"],
    "Department":["CS","IT","ENTC","Mech","Civil"],
    "CGPA":[8.2,7.5,9.1,6.8,8.7]
}

df = pd.DataFrame(data)
df.to_csv("data1.csv",  index=False)
print(df)

   Roll_No Gender Department  CGPA
0      101      F         CS   8.2
1      102      M         IT   7.5
2      103      F       ENTC   9.1
3      104      M       Mech   6.8
4      105      F      Civil   8.7

In [ ]:
print(df.shape)

(5, 4)

In [ ]:
print(df.size)

20

In [ ]:
print(df.describe())

          Roll_No     CGPA
count    5.000000  5.00000
mean   103.000000  8.06000
std      1.581139  0.92358
min    101.000000  6.80000
25%    102.000000  7.50000
50%    103.000000  8.20000
75%    104.000000  8.70000
max    105.000000  9.10000

In [ ]:
#Upload the Dataset
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Cars93.csv')
display(df)

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB
None

In [ ]:
df.shape

(93, 10)

In [ ]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [ ]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.sample(5)

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
13,Chevrolet,Camaro,Sporty,15.1,19,Driver & Passenger,160,4,25.0,13.0
14,Chevrolet,Lumina,Midsize,15.9,21,NaN,110,6,28.5,16.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
60,Mercury,Cougar,Midsize,14.9,19,NaN,140,5,28.0,15.0
48,Lexus,ES300,Midsize,28.0,18,Driver only,185,5,27.5,14.0

In [ ]:
df.isnull().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.nunique()

Manufacturer      32
Model             93
Type               6
Price             81
MPG.city          21
AirBags            2
Horsepower        57
Passengers         6
Rear.seat.room    24
Luggage.room      16
dtype: int64